theme: jekyll-theme-minimal
title: Bluestem
email: taylor@bluestem.solutions
description: >
  Bluestem builds solutions for your problems.  Take a look at what we've already built, or reach out to have a solution built just for you.
baseurl: ''
url: 'http://localhost:4000'
include: ['pages']
github_username: bluestemso
markdown: kramdown
